### ISSUE TITLE
[REQUEST] Matters to be completed by June 17

### ISSUE THREAD

**Issue by dolphin1404** [dolphin1404/GoodMenu_CBNUOS#32]
## Problem
We have to submit all of codes due to June 17.
So we must wrap up matters the below things due to by 10 p.m. today.

18일 00시까지 산출물 및 코드를 제출해야 합니다.
따라서 계획서에 맞게 22시까지 아래 사항을 마무리해주세요.

각 해당 task들 받아서 커밋해주시고 한꺼번에 PR 올려주세요.

## Task 👍 

- [x] Info 부분 수정.
- [x] 메인에서 보이는 카테고리는 지역만 보이게 하고, 교내시설, 편의점, atm 카테고리는 왼쪽 사이드바에 있는 학교 정보 안으로.
- [x] 왼쪽 navbar에 적절한 아이콘 재배정 (카테고리 아이콘도 적절히) <fontawesome 사이트 이용> : 학교 아이콘과 별 아이콘을 서로 변경
- [x] 도서관 자료실 운영 시간도 추가로 보여주기.
- [ ] 학생회 (자연대, 전정대만 추가) 카테고리를 교내 정보 안에 카테고리 버튼 만들어서 보여주기
- [x] 교내시설 시간이라 적힌 탭을, 교내 정보로 타이틀 변경 후 위는 위에서 말한 학생회 각 버튼 만들고 지도에 마커 달리 표시하고 리스트를 탭 안에 띄어주고, 그 아래에 현재처럼 시간 알려주는 걸로. (예시로 타이틀은 h1 태그, 교내시설 운영시간은 h3 태그 이런식으로 구분해도 될 듯)
- [x] 정보탭 안에 QR 코드 이미지 삽입 

## Example
![image](https://github.com/dolphin1404/GoodMenu_CBNUOS/assets/43460702/0de41f12-9e82-4d16-be98-424f94fb80f8)
> 내 주변 맛집인데 아이콘이 학교 아이콘 

![image](https://github.com/dolphin1404/GoodMenu_CBNUOS/assets/43460702/92b234b8-e3f0-4f19-93de-aa2517be6ab4)
> QR 코드

**Comment by dolphin1404** [comment]
Finish
